### ISSUE TITLE
TimeStepInSeconds node repeated

### ISSUE THREAD

**Issue by aclerc** [peterdougstuart/PCWG#1]
Data set 1 currently fails the benchmark because TimeStepInSeconds is missing from the config xml.

TimeStepInSeconds is often in both the Analysis xml and config xml.  This duplication should be resolved, the config xml is likely the best place for TimeStepInSeconds as it is a property of the dataset.

**Comment by joekane3** [comment]
TimeStepInSeconds is now in dataset config files as of #11. Logic is applied in the analysis section to work out the minimum time difference. This assumes that the data in each dataset are of the same time period. To break this assumption we can have an extra column "TimeInSeconds" in analysis.dataFrame or change the dataframe's index from datetimeindex to period index.

**Comment by joekane3** [comment]
That is to say the current assumption is implicit, I.e. no explicit exception is raised if dataset's TimeStepInSeconds are different.

**Comment by joekane3** [comment]
now made explicit in 29038ce6a4d8c39026d3723fe556a70491195707 -  inherits value from first dataset, raises exception if any subsequent datasets have a different TimeStepInSeconds .
