### ISSUE TITLE
Density Corrected Wind Speed Input

### ISSUE THREAD

**Issue by lcameron05** [peterdougstuart/PCWG#106]
If a wind speed signal that has been density corrected outside the tool is input directly the tool has no way to know that the correction has already been performed. Wind Speed column definitions should have a "Density Corrected" property that defaults to False.

In the context of PCWG Share 1 this is a problem if density correction is applied externally and then density (or pressure and temperature) are defined in the dataset config as the analysis will then automatically apply density correction.

**Comment by peterdougstuart** [comment]
This feature is now added to the 'Advanced' tab on a dataset.
