### ISSUE TITLE
PCWG Share 1 report fails if inner range A fails

### ISSUE THREAD

**Issue by DanielMarmander** [peterdougstuart/PCWG#108]
If there isn't enough data in the inner range type A, then calculations are not finished and report not produced.

**Comment by lcameron05** [comment]
See also:
https://github.com/peterdougstuart/PCWG/commit/1f42d01aeef4cfc921e5ac80eec4faf15ad18b52
https://github.com/peterdougstuart/PCWG/commit/dc8ad06c55ef09dfaa253bfc94568176eef15944
