### ISSUE TITLE
Four cell matrix labels in output files are incorrect

### ISSUE THREAD

**Issue by AndyClifton** [peterdougstuart/PCWG#112]
The four cell matrix labeling in the output file is incorrect. The cells are labeled in row 27 as `"LWS-LTI"`,`"LWS-HTI"`,`"HWS-HTI"`, and `"HWS-HTI"`. I believe F27 should be labeled as `"HWS-LTI"`.

**Comment by lcameron05** [comment]
Hi Andy,

Yes, you are correct. I can confirm that the values being reported in F28, F29 and F30 do indeed correspond to "HWS-LTI". This is simply a typographical error in the template.

Thanks for reporting this,
Lee.
