### ISSUE TITLE
Specific power calculation appears incorrect

### ISSUE THREAD

**Issue by AndyClifton** [peterdougstuart/PCWG#116]
Values of specific power appear incorrect. Values should be in the region 200-300 w/m<sup>2</sup>; reported values in cell C26 on the "Meta Data" tab are around 3,000.

**Comment by lcameron05** [comment]
Hi Andy,

Thanks for spotting this. Rated power is being reported instead of specific power.

**Comment by lcameron05** [comment]
@AndyClifton The fix I have added expresses specific power in units of kW/m^2 as the convention in the tool generally is to express power in kW. This can be easily changed if you prefer to have it in W/m^2.

**Comment by AndyClifton** [comment]
Can you add units to the text in column B of the "Meta Data" tab, please?

**Comment by lcameron05** [comment]
Hi Andy. Yes this can be added. I have opened a new issue to ensure I don't forget to add this in before release:

**Comment by lcameron05** [comment]
https://github.com/peterdougstuart/PCWG/issues/118
