### ISSUE TITLE
Anonymized wind speeds

### ISSUE THREAD

**Issue by Inyaki** [peterdougstuart/PCWG#12]
In order to create more consistent anonymized reports, the unitless wind speed should be reviewed.

As a suggestion, the wind speeds should be re-scaled so that:
   1) Unitless speed is zero (0.0) at cut in
   2) Unitless speed is one (1.0) at the nominal wind speed in zero turbulence power curve
   3) Unitless speed is two (2.0) at cut out

This way, the aggregation of the anonymized reports should be more consistent, regardless the air density or the machine size.

**Comment by joekane3** [comment]
This to be addressed before June PCWG meeting

**Comment by joekane3** [comment]
![image](https://cloud.githubusercontent.com/assets/9845637/8230993/2105276c-15bd-11e5-9476-d00e60d43747.png)


A quick paint job to clarify my understanding of the issue and how I have solved it.

**Comment by joekane3** [comment]
Fixed in 697e8630da59d780ad44a45c3e941472722d704b
