### ISSUE TITLE
AEP padding

### ISSUE THREAD

**Issue by GregMJP** [peterdougstuart/PCWG#134]
Measured power values for wind speed bins in the AEP with no (or possibly very low) data count are being padded/gap filled with the measured power from the max wind speed bin. This appears to only occur if there are values in wind speed bins above and below the bins in question. See example files linked [here](http://ecm1/livelink/llisapi.dll/properties/40325065).

**Comment by lcameron05** [comment]
To add to this, the AEP sheet in the Excel report still has the correct per bin values, even for incomplete bins, so until a fix is implemented you can sum the energy columns to get the correct value.

**Comment by lcameron05** [comment]
This is the problematic piece of code:

https://github.com/peterdougstuart/PCWG/blob/master/Analysis.py#L1227

It just pads when the bin is undefined, it needs to interpolate from adjacent bins using the specified interpolation method in cases when the bin is less than the last complete bin. This operation of interpolating intermediate bins should possibly be carried out before passing to the padder.

**Comment by lcameron05** [comment]
My fix does not account for padding below the first complete bin so reopening to solve this.
