### ISSUE TITLE
Issue with exporting reports

### ISSUE THREAD

**Issue by jnmosullivan** [peterdougstuart/PCWG#148]
Hi, I'm currently using the 0.5.14 version of the PCWG tool, and when I try to export a report based on the accompanying Dataset 1, I get the following error message:

ERROR Exporting Report: Unexpected data type <type 'numpy.int64'>

How do I avoid this? I am not particularly experienced with programming, I'm just using the program as a part of my internship.

**Comment by lcameron05** [comment]
Hi @jnmosullivan 

These errors are quite hard for us to debug without seeing the analysis and dataset configuration xmls files. As your example currently is based on the open source PCWG dataset 1, would you mind sharing the xml config files? This would enable me to debug the issue properly.

If you are indeed happy to share these two xml files, they can be attached to a comment on this issue thread. You may need to put them in a zip file first GitHub restricts the extensions allowed for attached files.

Thanks.

**Comment by jnmosullivan** [comment]
Here they are. I can see now that my original message did not include the complete error message (I assume the triangle brackets made github see it as markup). The error message says that the unexpected datatype is numpy.int64 if that helps in any way.

[jnmo.zip](https://github.com/peterdougstuart/PCWG/files/451364/jnmo.zip)

**Comment by lcameron05** [comment]
This was due to the fact that `xlwt` (package we use to write the Excel report) requires all numerical data to be recognisable as type `int` or `float`. `numpy.int64` type is not recongised as `int` (`isinstance(np.int64(1), int)` returns `False`, whereas `isinstance(np.int32(1), int)` returns `True`). I am about to push a fix.

@jnmosullivan This will then be fixed in the Python code but will not be in the Windows executable until next release. I think we intend to release a new version very soon.

**Comment by lcameron05** [comment]
Hi @jnmosullivan ,
We have now released version [version 0.6.0](https://github.com/peterdougstuart/PCWG/releases/tag/0.6.0) which will enable you to export your report. 

There is a small change in the structure of the dataset and analysis configuration xmls that you will see highlighted in the v0.6.0 release notes; some turbine details (hub height, diameter, rated power, cut out/in wind speed) have been moved from analysis configuration to dataset configuration. I have updated your xml configuration files to reflect this change and attached them to in the zip file below. Please use these to run your analysis with the new version of the tool.

[Issue 148 configs.zip](https://github.com/peterdougstuart/PCWG/files/461297/Issue.148.configs.zip)
