### ISSUE TITLE
Hamburg Bug: Specified curve selection

### ISSUE THREAD

**Issue by joekane3** [peterdougstuart/PCWG#19]
From Hamburg meeting 25/03/15

The specified curve needs to be selected even if it not being used. This should be able to be blank if not required for other settings.

**Comment by joekane3** [comment]
I think this is not just input validation but also a setting to skip object creation is needed in analysis.py, this might have been added already?

**Comment by joekane3** [comment]
should be easy to do before next release.

**Comment by lcameron05** [comment]
I think I have fixed this in my latest commit:

https://github.com/lcameron05/PCWG/commit/2a2a569aa3609ad032bb3d227beb5ca8dd342b75

**Comment by lcameron05** [comment]
Fixed https://github.com/peterdougstuart/PCWG/pull/33

**Comment by joekane3** [comment]
fixed in code but not in GUI I believe
