### ISSUE TITLE
New dataset creation error

### ISSUE THREAD

**Issue by coillarach** [peterdougstuart/PCWG#30]
When trying to create a new analysis at least one dataset is required. Trying to create a new dataset config file fails with:
"ERROR creating dataset config: Unknown hub wind speed mode: None"

Incorrect defaults?

**Comment by joekane3** [comment]
https://github.com/joekane3/PCWG/commit/7f6a797e6543ea8e43275f134962c58442aab804

I think this is fixed. You're right Brain, default value is 'None' when the GUI validation code was expected 'Specified' or 'Calculated'. Should now expect the default value too. Will double check this works next week.

@peterdougstuart see above for GUI fix, you may want to solve in a different way but the specif line is here: https://github.com/joekane3/PCWG/commit/7f6a797e6543ea8e43275f134962c58442aab804#diff-a3803fe2234e186a0798f2820f406895R1185 method is calibrationMethodChange() in pcwg_tool.py

**Comment by joekane3** [comment]
fixed by peter with https://github.com/peterdougstuart/PCWG/commit/4665a782b2d26e59e43fb21555aa2bdbaa7545e7
