### ISSUE TITLE
Power curve sensitivity to given variable

### ISSUE THREAD

**Issue by lcameron05** [peterdougstuart/PCWG#32]
Add method to analysis.py that calculates the sensitivity to a given data column using the method outlined here:
http://www.pcwg.org/proceedings/2014-04-01/02-Validation-Analysis-Turbulence-Correction-Alex-Clerc-RES.pdf

**Comment by lcameron05** [comment]
The following commit adds this functionality. Still needs to produce plots on report generation.

https://github.com/lcameron05/PCWG/commit/825228e7b35babbe65c7f7169953dc62cf0a081b

**Comment by lcameron05** [comment]
Plots now produced. Some fixes to the calculation logic.

https://github.com/lcameron05/PCWG/commit/f9bfb4409894db2025b00917d5127d8760ff93e9

**Comment by joekane3** [comment]
Added in #33
