### ISSUE TITLE
Binning bug

### ISSUE THREAD

**Issue by coillarach** [peterdougstuart/PCWG#34]
This code from binning.py appears to produce one more bin that necessary:

1        start_of_first_bin = self.centerOfFirstBin - self.binWidth
2        end_of_last_bin = self.centerOfLastBin + self.binWidth
3        self.numberOfBins = (end_of_last_bin - start_of_first_bin)/self.binWidth

Lines 1 & 2 should use self.binWidth/2

Does the binning code handle half-closed intervals?

**Comment by joekane3** [comment]
``` python 
>>> self.binCenterForFirstCenterAndWidth(3.7499999, self.centerOfFirstBin, self.binWidth)
Out[11]: 3.5
>>> self.binCenterForFirstCenterAndWidth(3.500001, self.centerOfFirstBin, self.binWidth)
Out[12]: 3.5
>>> self.binCenterForFirstCenterAndWidth(3.7499999, self.centerOfFirstBin, self.binWidth)
Out[13]: 3.5
>>> self.binCenterForFirstCenterAndWidth(3.75000001, self.centerOfFirstBin, self.binWidth)
Out[14]: 4.0
>>> self.binCenterForFirstCenterAndWidth(3.75, self.centerOfFirstBin, self.binWidth)
Out[15]: 4.0
>>> self.binCenterForFirstCenterAndWidth(3.25, self.centerOfFirstBin, self.binWidth)
Out[16]: 3.5
>>> self.binCenterForFirstCenterAndWidth(3.249999, self.centerOfFirstBin, self.binWidth)
Out[17]: 3.0
```

If I understand correctly, the bins are defined so that 3.5 represents [3.25,3.75)

**Comment by joekane3** [comment]
You're correct about the extra bin production, although this shouldn't affect anything other than storing one tiny extra float.

I propose the following solution in here d6749c723d2d4bcca9cf7273c9f4802ef525ae16 :

``` python
        start_of_first_bin = self.centerOfFirstBin - (0.5*self.binWidth)
        end_of_last_bin = self.centerOfLastBin + (0.5*self.binWidth)
```
