### ISSUE TITLE
Use collector nodes in xml

### ISSUE THREAD

**Issue by aclerc** [peterdougstuart/PCWG#38]
Tidy up config xml's (in particular the Dataset config) using collector nodes.  This will make the code more robust and make it easier to create a schema in future

For example filters with clauses currently have this structure:

```xml
<Filter>
    <Relationship>
        <Conjunction></Conjunction>
        <Clause></Clause>
        <Clause></Clause>
    </Relationship>
</Filter>
```

Using a collector node we should instead have:
```xml
<Filter>
    <Relationship>
        <Conjunction></Conjunction>
        <Clauses>
            <Clause></Clause>
            <Clause></Clause>
        </Clauses>
    </Relationship>
</Filter>
```

**Comment by joekane3** [comment]
see Filters page on wiki
