### ISSUE TITLE
Tidy up multiple values in xml

### ISSUE THREAD

**Issue by aclerc** [peterdougstuart/PCWG#39]
There are some nodes such as FilterValue which currently can accept multiple values in certain situations, for example:

```xml
<Filter>
    <DataColumn>InflowAngle</DataColumn>
    <FilterType>Between</FilterType>
    <FilterValue>2,358</FilterValue>
</Filter>
```
It would be good to make this more explicit, e.g.:
```xml
<BetweenFilter>
    <DataColumn>InflowAngle</DataColumn>
    <FilterStartValue>2</FilterStartValue>
    <FilterEndValue>358</FilterEndValue>
</BetweenFilter>
```
Tidying this up would make the code more robust and make it easier to define the xml schema in future

**Comment by joekane3** [comment]
between no longer exists
