### ISSUE TITLE
GUI dataset column selection for .csv files

### ISSUE THREAD

**Issue by lcameron05** [peterdougstuart/PCWG#43]
In the GUI selecting a dataset column (for example selecting the column to assign to "Hub Wind Speed" or "Power" under "Measurement Settings") does not work when the input file is delimited by commas. Tab delimited input files are handled correctly.

**Comment by joekane3** [comment]
fixed with selection for delimiter in GUI:

https://github.com/peterdougstuart/PCWG/commit/76f3a030bb4eb1d3d4acda1d3f498d26a4400153
