### ISSUE TITLE
Sensitivity analysis, variation metric

### ISSUE THREAD

**Issue by lcameron05** [peterdougstuart/PCWG#44]
For each variable studied in the sensitivity analysis it is possible to define a variation metric based on the absolute deviation of each of the categorised power curves from the mean curve. 

A significance threshold can also be defined by calculating the variation metric with respect to a random variable.

**Comment by lcameron05** [comment]
Added the calculation. Plotting of results bar chart still needs work.

https://github.com/lcameron05/PCWG/commit/6765f7a8f9b5b689f0498b2d040efd6c2f068d3f

**Comment by joekane3** [comment]
This seems to work well and is very useful, i think we should get this finalised and in the release before next week.
