### ISSUE TITLE
Unspecified inner range

### ISSUE THREAD

**Issue by lcameron05** [peterdougstuart/PCWG#48]
When comparison to the inner range power curve is not desired as an output, it is still possible that the calculation of initialZeroTurbulencePowerCurve can result in the analysis failing (due to non-convergence of the numerical method).

When comparison to the inner range is not desired this should not result in an exception being thrown. Furthermore, definition of inner range turbulence in the analysis xml need not be required.

**Comment by joekane3** [comment]
@lcameron05 can we think of a way of doing it other than in: #49 ?

if not then feel free to merge pull request.

**Comment by joekane3** [comment]
I think this is something that can cause a few snags when running analyses. Let's make and include the decision before releasing next week.
