### ISSUE TITLE
Multiple dataset causes exception

### ISSUE THREAD

**Issue by lcameron05** [peterdougstuart/PCWG#57]
The following line causes an exception to be thrown as it tries to take a slice of the data frame between two lines as if the index was a datetime, however, at this point in code execution the data frame has an integer index:

https://github.com/peterdougstuart/PCWG/blob/master/Analysis.py#L289

This relates to printed line "KNOWN BUG FOR CONCURRENT DATASETS":

https://github.com/peterdougstuart/PCWG/blob/master/Analysis.py#L278

**Comment by lcameron05** [comment]
I have fixed the exception with the following commit:

https://github.com/lcameron05/PCWG/commit/049b86a4e17617eff8fbb44de905c11bc3391172

However, the filters will still be applied incorrectly when the datasets are concurrent. This can be fixed by choosing the rows to add a dataset specific filter to based on timestamp and dataset name instead of only timestamp.

**Comment by joekane3** [comment]
added a line to mask by configuration name as well as dates.

https://github.com/peterdougstuart/PCWG/blob/eeb698da5786cea37149faefb6bbef25ed0f13e6/Analysis.py#L295

```python
mask = self.dataFrame[self.timeStamp] > datasetStart
mask = mask & (self.dataFrame[self.timeStamp] < datasetEnd)
mask = mask & (self.dataFrame[self.nameColumn] == dataSetConf.name)
```
