### ISSUE TITLE
Calibration direction

### ISSUE THREAD

**Issue by joekane3** [peterdougstuart/PCWG#59]
Had a bit of trouble with the calibration directions and to avoid confusing i propose that the following amendment to the xml is made:
```xml
<CenterOfFirstSector>5</CenterOfFirstSector>
<CalibrationDirections>
			<CalibrationDirection>
				<Direction>225.000000</Direction>
				<Slope>1.003000</Slope>
				<Offset>-0.020000</Offset>
				<Active>1</Active>
			</CalibrationDirection>
</CalibrationDirections>
```

to become
```xml
<CenterOfFirstSector>5</CenterOfFirstSector>
<CalibrationDirections>
			<CalibrationDirection>
				<DirectionCentre>225.000000</DirectionCentre>
				<Slope>1.003000</Slope>
				<Offset>-0.020000</Offset>
				<Active>1</Active>
			</CalibrationDirection>
</CalibrationDirections>
```

i.e. make it more explicit that the centre of the bin is 225, not the start or anything else.

**Comment by joekane3** [comment]
Would require GUI change too.

**Comment by MVAppleby** [comment]
Believe I changed it in my recent commit to temp.
https://github.com/MVAppleby/PCWG/commit/8bc58910ff2bbd82143aa67d350cc7f0d55a6548
