### ISSUE TITLE
Callibration filters

### ISSUE THREAD

**Issue by MVAppleby** [peterdougstuart/PCWG#68]
There is currently no way to add calibration filters on the GUI. The XML is similar to that of the filters section of the GUI
![callibation settings](https://cloud.githubusercontent.com/assets/13198775/8524740/ee565fca-23f4-11e5-985e-6a223f5dd1cf.png)

**Comment by MVAppleby** [comment]
The fix for the calibration filters can be found here: https://github.com/MVAppleby/PCWG/commit/710983d236bf2a0f5d8d2ce628fdd391821c3093#diff-84cd3e0c9afd394d870eb748f0b20551R974

The GUI now looks like this 
![callibration filters](https://cloud.githubusercontent.com/assets/13198775/8565752/5768b8d0-2550-11e5-8854-252f5da2bab6.png)

**Comment by joekane3** [comment]
Any idea why those dates look different in the exclusions box?

**Comment by joekane3** [comment]
#74 is similar. If fixed, please reference issue in your pull request and then close them them.

**Comment by MVAppleby** [comment]
I managed to recreate the error. I believe it has something to do with how the GUI inputs data tot he table and extracts it from the XML file. I changed the format from %d/%m/%Y %H:%M to %d/%m/%Y %H:%M:%S before closing and reopening the file. The dates int he exclusions i had already inputed changed but the new date did not.

![image](https://cloud.githubusercontent.com/assets/13198775/8616297/0f4286e6-26f2-11e5-9648-9b26f8efbb80.png)

After reopening the dataset dialog:

![image](https://cloud.githubusercontent.com/assets/13198775/8616330/547784dc-26f2-11e5-8175-b29b0284fa16.png)

AFter changing the format back and reopening:

![image](https://cloud.githubusercontent.com/assets/13198775/8616347/766b6a40-26f2-11e5-9aed-f1f20d8a20e6.png)

It appears to be a difference in the reading and inputting of the dates
