### ISSUE TITLE
Unable to edit dates on the GUI

### ISSUE THREAD

**Issue by MVAppleby** [peterdougstuart/PCWG#71]
When adding dates on the GUI, the okay button on the date window is unresponsive. however, if a XML file is used with the dates already configured for the program, they appear on the GUI but cannot be edited (They can be deleted but a new ate cannot be entered.)

**Comment by MVAppleby** [comment]
I have fixed the validation function for the okay button on the DatePickerDialog which wasn't function due to an incomplete validation function that only returned 0. https://github.com/MVAppleby/PCWG/commit/0dcd2bcf0c126baac54e2a02db45b0994ec9ab8e#diff-a3803fe2234e186a0798f2820f406895L1189

**Comment by joekane3** [comment]
merged in #72 - thanks @MVAppleby
