### ISSUE TITLE
Specified Power Curve Editing

### ISSUE THREAD

**Issue by MVAppleby** [peterdougstuart/PCWG#73]
A new specified power curve cant be created and a blank specified power curve template with a turbulence and denstiry blank also cannot be edited. Therefore the GUI can only edit/use precreated xml specified power curves.

**Comment by MVAppleby** [comment]
Solved problem. There was an New Button but it was hidden beneath the edit button. Have moved it so it is now above however it is in the same line as Diameter as I don't know how to edit the height of the fileopenentry box.

**Comment by MVAppleby** [comment]
https://github.com/MVAppleby/PCWG/commit/5139678fd22d3d40856e37d0a825e6f4773dc23a

**Comment by MVAppleby** [comment]
(Just in case I misunderstood the issue)

**Comment by joekane3** [comment]
yup, seems fine.
