### ISSUE TITLE
Shear/REWS tip row (inside listbox)

### ISSUE THREAD

**Issue by MVAppleby** [peterdougstuart/PCWG#80]
The tip row inside these listboxes no longer affects the reading of the values, however they can still be deleted by the user unlike the tips in the other listboxes

**Comment by joekane3** [comment]
I think this is the "column headers" rather than the tips, which appear to the right of the listbox.

**Comment by MVAppleby** [comment]
Fix at this line of code https://github.com/MVAppleby/PCWG/commit/c8787b070b10b7ca8082d04663280f64205007bf#diff-a3803fe2234e186a0798f2820f406895R2297
