### ISSUE TITLE
Filters deselecting themselves

### ISSUE THREAD

**Issue by peterdougstuart** [peterdougstuart/PCWG#91]
It was observed during the PCWG meeting that sometimes when a user enters a filter it can be deselected/forgotten in the UI.

**Comment by MVAppleby** [comment]
I think this was fixed recently, the filters should be saved when added in the UI.
The screenshots aren't very clear but I'd be happy to demo this for you if need be.

![filters 1](https://cloud.githubusercontent.com/assets/13198775/9627726/de443c42-515d-11e5-9a98-b1f7cf3c1079.png)
![filters 2](https://cloud.githubusercontent.com/assets/13198775/9627728/de468312-515d-11e5-96dc-dd5a9de90ea9.png)
![filters 3](https://cloud.githubusercontent.com/assets/13198775/9627727/de46090a-515d-11e5-97f7-e254dbd88260.png)
![filters 4](https://cloud.githubusercontent.com/assets/13198775/9627729/de47a418-515d-11e5-85d3-d9f64c2e91c5.png)

**Comment by MVAppleby** [comment]
I can't remember which commit this was fixed in but I know that an update solving the error message on the tool was fixed in this commit. https://github.com/peterdougstuart/PCWG/pull/78
