### ISSUE TITLE
Unique Reference Number

### ISSUE THREAD

**Issue by peterdougstuart** [peterdougstuart/PCWG#94]
The tool should calculate a unique reference number for each run. This could be some form of 'checksum' based on the contents of the raw data file, data config and analysis config.

This same reference number should be included on both the anonymous and non-anonymous reports in order to link the two reports for traceability.

**Comment by lcameron05** [comment]
The following Unique IDs are now generated and given in the anonymous report:
- A hash of the file contents of the analysis config xml. 
- Per dataset: 
    --An invariant random ID that does not change when changes to the dataset config are made
    --A hash of the file contents of the dataset config
- a hash of the contents of the time series file
All hashes of file contents ignore white space.
https://github.com/peterdougstuart/PCWG/pull/101
