### ISSUE TITLE
Incorrect Date Format (if two digit year in file)

### ISSUE THREAD

**Issue by peterdougstuart** [peterdougstuart/PCWG#95]
During the June 2015 PCWG meeting a working group member reported an 'Incorrect Date Format' error if they attempted to calculate a file with a two-digit representation of the date.

**Comment by MVAppleby** [comment]
I have adjusted the code for this on my 'temp' branch on line 1748 (incase the below link doesn't work)
https://github.com/peterdougstuart/PCWG/compare/master...MVAppleby:temp#diff-a3803fe2234e186a0798f2820f406895R1748

**Comment by lcameron05** [comment]
%y as opposed to %Y denotes a 2 digit date. This option is now in the date format drop down list and so this should be fixed.
