### ISSUE TITLE
Error if there isn't enough data in inner range

### ISSUE THREAD

**Issue by DanielMarmander** [peterdougstuart/PCWG#99]
At export anonymous report (this does not happen when exporting full report), the error "Exporting Anonymous Report: attempt to get argmax of an empty sequence" is raised. Changing inner range settings to include more data "fixes" the issue.

Inner range contains data, but there seems to be some bins or similar that are empty, and this causes problems at the creation of anonymous report.

**Comment by lcameron05** [comment]
The old anonymous report is now retired from the UI.
